name: flyinsky
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  provider: ^6.1.5
  rive: ^0.13.20
  connectivity_plus: ^6.1.3
  flutter_pdfview: ^1.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/splash_fly.riv
   - assets/checklist/